---
apiVersion: v1
kind: ConfigMap
metadata:
{{ include "cleveroperator.namespace" . | indent 2 }}
  name: clever-operator-configuration
data:
  config.toml: |
    [api]
    token = "{{ .Values.config.token }}"
    secret = "{{ .Values.config.secret }}"
    consumerKey = "{{ .Values.config.consumerKey }}"
    consumerSecret = "{{ .Values.config.consumerSecret }}"
