---
apiVersion: api.clever-cloud.com/v1
kind: Metabase
metadata:
  namespace: default
  name: metabase
spec:
  organisation: orga_<uuid v4>
  instance:
    region: par
    plan: plan_2925d534-7155-4521-8052-d068d7ce8915 # corresponds to the 'base' plan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: debian-metabase
  name: debian-metabase
  namespace: default
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: debian-metabase
  namespace: default
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: debian-metabase
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debian-metabase
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: debian-metabase
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: debian-metabase
  labels:
    app: debian-metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-metabase
  template:
    metadata:
      labels:
        app: debian-metabase
    spec:
      serviceAccountName: debian-metabase
      automountServiceAccountToken: true
      containers:
        - image: debian:bullseye-slim
          imagePullPolicy: Always
          name: debian-metabase
          command:
            - "sleep"
            - "3600"
          env:
          - name: METABASE_URL
            valueFrom:
              secretKeyRef:
                name: metabase-secrets
                key: METABASE_URL
          resources:
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 64M
              cpu: 100m
