---
apiVersion: api.clever-cloud.com/v1
kind: Keycloak
metadata:
  namespace: default
  name: keycloak
spec:
  organisation: orga_<uuid v4>
  instance:
    region: par
    plan: plan_3819e4b3-cc6d-4847-9f02-0db93212956c # corresponds to the 'base' plan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: debian-keycloak
  name: debian-keycloak
  namespace: default
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: debian-keycloak
  namespace: default
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: debian-keycloak
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debian-keycloak
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: debian-keycloak
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: debian-keycloak
  labels:
    app: debian-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-keycloak
  template:
    metadata:
      labels:
        app: debian-keycloak
    spec:
      serviceAccountName: debian-keycloak
      automountServiceAccountToken: true
      containers:
        - image: debian:bullseye-slim
          imagePullPolicy: Always
          name: debian-keycloak
          command:
            - "sleep"
            - "3600"
          env:
            - name: CC_KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: CC_KEYCLOAK_ADMIN
            - name: CC_KEYCLOAK_FSBUCKET_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: CC_KEYCLOAK_FSBUCKET_ID
            - name: CC_KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: CC_KEYCLOAK_URL
            - name: CC_KEYCLOAK_POSTGRES_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: CC_KEYCLOAK_POSTGRES_ID
            - name: CC_KEYCLOAK_ADMIN_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: CC_KEYCLOAK_ADMIN_URL
            - name: CC_KEYCLOAK_ADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: CC_KEYCLOAK_ADMIN_DEFAULT_PASSWORD
            - name: CC_KEYCLOAK_JAVA_APPID
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: CC_KEYCLOAK_JAVA_APPID
          resources:
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 64M
              cpu: 100m
