---
apiVersion: api.clever-cloud.com/v1
kind: Matomo
metadata:
  namespace: default
  name: matomo
spec:
  organisation: orga_<uuid v4>
  instance:
    region: par
    plan: plan_87283ba6-617c-420d-8e37-3350a2fcdd66 # corresponds to the 'beta' plan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: debian-matomo
  name: debian-matomo
  namespace: default
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: debian-matomo
  namespace: default
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: debian-matomo
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debian-matomo
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: debian-matomo
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: debian-matomo
  labels:
    app: debian-matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-matomo
  template:
    metadata:
      labels:
        app: debian-matomo
    spec:
      serviceAccountName: debian-matomo
      automountServiceAccountToken: true
      containers:
        - image: debian:bullseye-slim
          imagePullPolicy: Always
          name: debian-matomo
          command:
            - "sleep"
            - "3600"
          env:
            - name: MATOMO_URL
              valueFrom:
                secretKeyRef:
                  name: matomo-secrets
                  key: MATOMO_URL
          resources:
            requests:
              memory: 64M
              cpu: 100m
            limits:
              memory: 64M
              cpu: 100m
